### ISSUE TITLE
Print additional content section on another page

### ISSUE THREAD

**Issue by alexfaley** [Igor-Vladyka/leaflet.browser.print#133]
Hey there

I want to print addtional section on another page.
For this issue i tried use css rule like this 
```css
       @media print {
            .story {
                page-break-after: always;
                page-break-before: always;
                page-break-inside: avoid;
            }
        }
 ```
Here you can find full example https://jsfiddle.net/an8e9ovc/1/
        
When is printing via standard way (Ctrl+P) in result document three page, but when I print via leaflet.browser.print in result document only single page.
How I can insert page  break inn generation result.
